### ISSUE TITLE
CROSS megamd when nilavu launches Java application it causes the following error

### ISSUE THREAD

**Issue by arunkumarsekar06** [megamsys/megamd#172]
level=debug msg="Cartons [id: ASM1282373458558320640\nname: chernenko\ncartonsid: AMS1282373458621235200\ntosca: tosca.app.java\nimageversion: 8.x\ncompute:\n  cpushare: \"0.5\"\n  memory: \"896\"\n  swap: \"\"\n  hdd: \"10\"\ndomainname: megambox.com\nprovider: one\npublicip: \"\"\nenvs:\n- name: domain\n  value: megambox.com\n- name: sshkey\n  value: test@megam.com_test_megam\n- name: provider\n  value: one\n- name: cpu\n  value: \"0.5\"\n- name: ram\n  value: \"896\"\n- name: version\n  value: 8.x\nboxes:\n- id: COM1282373458562514944\n  cartonsid: AMS1282373458621235200\n  cartonid: ASM1282373458558320640\n  cartonname: chernenko\n  name: ovary\n  level: 3\n  domainname: \"\"\n  tosca: tosca.app.java\n  imageversion: \"\"\n  compute:\n    cpushare: \"0.5\"\n    memory: \"896\"\n    swap: \"\"\n    hdd: \"10\"\n  repo:\n    type: source\n    source: \"\"\n    oneclick: \"null\"\n    url: https://github.com/megamsys/java-spring-petclinic.git\n    hook: null\n  status: \"\"\n  provider: \"\"\n  publicip: \"\"\n  commit: \"\"\n  address: null\n]" 
time="2015-11-28T18:34:31+05:30" level=debug msg="\x1b[1;36;10mCREATE CARTON AMS1282373458621235200\x1b[0m" 
panic: interface conversion: interface is nil, not provision.GitDeployer

goroutine 25 [running]:
github.com/megamsys/megamd/carton.deployToProvisioner(0xc82002e140, 0x7fd6f64979d8, 0xc82025b8e0, 0x0, 0x0, 0x0, 0x0)
	/home/megam/code/megam/packager/megamd/build/trusty/megamd/src/github.com/megamsys/megamd/carton/deploy.go:76 +0x2d7

**Comment by indykish** [comment]
The problem is "Components don't have Provider name `[one, docker]'. Added a fix where by if there is no `provider name` in the component, then grab it from assembly
