### ISSUE TITLE
When creating app it set a VM name without .megambox.com

### ISSUE THREAD

**Issue by arunkumarsekar06** [megamsys/megamd#174]
opennebula show's the app name only(missing .megambox.com).

**Comment by indykish** [comment]
Lets test it out for a torpedo. 
@thomasalrin  your thoughts ?

**Comment by thomasalrin** [comment]
@indykish In future, if we allow users to change domain, it will be the issue.

**Comment by indykish** [comment]
@thomasalrin  ok, this is a bug, it needs to be there and we need to fix it.
