### ISSUE TITLE
CNAME missing args error for launching JAVA APP using java-spring-petclinic 

### ISSUE THREAD

**Issue by arunkumarsekar06** [megamsys/megamd#176]
"\x1b[1;32;10m  => step 1: add-new-route action\x1b[0m" 
time="2015-11-30T14:53:31+05:30" level=debug msg="route53 ready" 
 => step 1: add-new-route action error - CNAME missing args. [cname (and/or) ip] needed.\x1b[0m" 
time="2015-11-30T14:53:31+05:30" level=debug msg="\x1b[1;31;10m  => step 0: change-state-machine action\x1b[0m" 
time="2015-11-30T14:53:31+05:30" level=debug msg="  set status[COM1283041996826607616] of machine (megam., error)" 
time="2015-11-30T14:53:31+05:30" level=debug msg="  notify megam._log"

**Comment by indykish** [comment]
@arunkumarsekar06  May not be a megamd issue. Somebody isn't sending the value `megambox.com`. Probably nilavu.
