### ISSUE TITLE
while click overview page after creating Route53 record 

### ISSUE THREAD

**Issue by vijaykanthm28** [megamsys/megamd#195]
ERR    9 (192.168.1.105:4150) IO error - EOF
2016/01/20 12:25:52 Handler: topic=theta.megambox.com_log channel=clients
panic: send on closed channel

goroutine 1396 [running]:
github.com/megamsys/megamd/provision.dumpLog.func1.1(0xc82026e000, 0xc82052a570)
	/home/megam/code/workspace/packager/megamd/build/trusty/megamd/src/github.com/megamsys/megamd/provision/log.go:59 +0x241
created by github.com/megamsys/megamd/provision.dumpLog.func1
	/home/megam/code/workspace/packager/megamd/build/trusty/megamd/src/github.com/megamsys/megamd/provision/log.go:61 +0x3e

goroutine 1 [chan receive]:
github.com/megamsys/megamd/cmd/megamd/run.(*Start).Run(0xc82012f0a0, 0xc820134960, 0x0, 0x0)
	/home/megam/code/workspace/packager/megamd/build/trusty/megamd/src/github.com/megamsys/megamd/cmd/megamd/run/command.go:84 +0x7b6
github.com/megamsys/libgo/cmd.(*Manager).Run(0xc820178370, 0x0, 0x0, 0x0)
	/home/megam/.go/src/github.com/megamsys/libgo/cmd/cmd.go:184 +0x1ed1
main.main()
	/home/megam/code/workspace/packager/megamd/build/trusty/megamd/src/github.com/megamsys/megamd/cmd/megamd/main.go:52 +0xba

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1721 +0x1

**Comment by indykish** [comment]
@vijaykanthm28  so it works in the new launch. Lets keep a tab on it, and debug to see if there is an issue.
