### ISSUE TITLE
log does not view logs continuously

### ISSUE THREAD

**Issue by vijaykanthm28** [megamsys/megamd#199]

**Comment by indykish** [comment]
As i tested it today, the logs are shown from megamd.. We need to do more unit testing by connecting to **one** from local.

@rajthilakmca  Take a look at this.

**Comment by indykish** [comment]
As i tested it today, the logs are shown only when we run with the flag `-v`

```
log.Debugf("testing")  //only will print if -v is present
```

@vijaykanthm28  Please add the flag `-v` in `upstarts` of `megamd` and `gulp` in `packager`

@megamsys/megam-dev  When everybody tests stuff, just check the following.
- When an user clicks overview, are we showing the log as soon as it arrives ?
- When an user clicks overview after 1 minute, are we showing ``all`` the logs ?
