### ISSUE TITLE
Free snapshots doesn't work 

### ISSUE THREAD

**Issue by vijaykanthm28** [megamsys/megamd#433]
User has ability to create snapshots of a VM. The `quota` table tells us the available `free` quota. 

The problem is  we don't limit the snapshot quota even after using the free limit.

### Analysis

The snapshot creation failure doesn't stop the action pipeline and hence it doesn't reduce the free snapshot quota.

**Comment by indykish** [comment]
@suganyakaliyamoorthy  Good luck, lets see some pull req on this issue.

**Comment by vijaykanthm28** [comment]
issue fixed
