### ISSUE TITLE
Demo: Quota based plan is not work.

### ISSUE THREAD

**Issue by rajesh-rajagopal** [megamsys/megamd#434]
Quota is not valid once user can launched a VM

**steps to reproduce:-**
Launched a VM from purchased quota after that delete a VM then the quota is not shown in UI, when i launched a VM it shows **insufficient fund**

**Comment by rajesh-rajagopal** [comment]
![image](https://cloud.githubusercontent.com/assets/18652643/25381379/20e9c6dc-29d1-11e7-8a3c-df6a67ea1e36.png)

**Comment by rajesh-rajagopal** [comment]
http://demo.virtengine.com/t/AMS4676497993087904547/ASM5329585973348414954/predeploy

**Comment by vijaykanthm28** [comment]
assembly doesn't send quota_id even user have remaining quota.
issue moved to https://gitlab.com/megamsys/nilavu/issues/1480
