### ISSUE TITLE
State problem in VM

### ISSUE THREAD

**Issue by vinomca-megam** [megamsys/megamd#442]
VM launch with unpaid .Vm cann't launch and show insufficient_fund. But it send me the mail by following.

Hey vino.v@megam.io

	
''Failed !

I hope you're having a great day today. There are some issues on your account that need your attention. There is an invoice(s) that are past due on your account. Please be aware that any invoices more than 0 days OR credit -1 amount past due are subject to suspend and more than 0 days OR credit -7 amount past due are subject to terminate.

GENERATED AT: 2017-05-10T13:07:51+03:00

DUE DATE: 2017-05-10T13:22:51+03:00

This mail is to intimate for terminate

If next due over dated patient-forest-8641.megambox.com will be unrecoverable.

If you can please make a payment on your outstanding invoices to avoid cancellation of your services we would greatly appreciate it.

If your account balance is zero and your invoice still shows as unpaid, you may need to apply credit to the invoice.

Please be aware that any servers that are reconnected after termination will incur a $10 reconnection fee.''

**Comment by vijaykanthm28** [comment]
issue fixed.

**Comment by vijaykanthm28** [comment]
issue is related to #446 it has to tested
